=== dchorn/XML/Practica2.2/Actividad4/defs.dtd
<!ELEMENT Defs (ThingDef)*>
<!ELEMENT ThingDef (defName,label,description,(statBases|pathCost)*,
graphicData,(uiIconScale|hideAtSnowDepth|ingestible)*,plant)>
<!ELEMENT statBases (MaxHitPoints,Flammability,Nutrition)>
<!ELEMENT graphicData (textPath,(graphicClass|drawSize|shadowData)*)>
<!ELEMENT shadowData (volume)>
<!ELEMENT plant (fertilityMin|fertilitySensitivity|growDays|leaflessGraphicPath|harvestWork|
maxMeshCount|visualSizeRange|topWindExposure|wildOrder|wildClusterRadius|wildClusterWeight)*>

<!ELEMENT defName (#PCDATA)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT MaxHitPoints (#PCDATA)>
<!ELEMENT Flammability (#PCDATA)>
<!ELEMENT Nutrition (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT uiIconScale (#PCDATA)>
<!ELEMENT growDays (#PCDATA)>
<!ELEMENT leaflessGraphicPath (#PCDATA)>
<!ELEMENT textPath (#PCDATA)>
<!ELEMENT drawSize (#PCDATA)>
<!ELEMENT graphicClass (#PCDATA)>
<!ELEMENT hideAtSnowDepth (#PCDATA)>
<!ELEMENT ingestible EMPTY>
<!ELEMENT fertilityMin (#PCDATA)>
<!ELEMENT fertilitySensitivity (#PCDATA)>
<!ELEMENT harvestWork (#PCDATA)>
<!ELEMENT maxMeshCount (#PCDATA)>
<!ELEMENT visualSizeRange (#PCDATA)>
<!ELEMENT topWindExposure (#PCDATA)>
<!ELEMENT wildOrder (#PCDATA)>
<!ELEMENT wildClusterRadius (#PCDATA)>
<!ELEMENT wildClusterWeight (#PCDATA)>
<!ELEMENT pathCost (#PCDATA)>

<!ATTLIST ThingDef ParentName CDATA #REQUIRED>

=== dchorn/XML/Practica2.2/Actividad4/defs.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE Defs SYSTEM "defs.dtd">
<Defs>
    <!--====================================== Carpets
======================================== -->
    <ThingDef ParentName="PlantBase">
        <defName>Plant_Grass</defName>
        <label>grass</label>
        <description>Wild grass. Grows anywhere there is a little light and minimally fertile ground.</description>
        <statBases>
            <MaxHitPoints>85</MaxHitPoints>
            <Flammability>1.3</Flammability>
            <Nutrition>0.50</Nutrition>
        </statBases>
        <graphicData>
            <textPath>Things/Plant/Grass</textPath>
            <graphicClass>Graphic_Random</graphicClass>
        </graphicData>
        <hideAtSnowDepth>0.5</hideAtSnowDepth>
        <ingestible />
        <plant>
            <fertilityMin>0.05</fertilityMin>
            <fertilitySensitivity>0.3</fertilitySensitivity>
            <growDays>2.5</growDays>
            <leaflessGraphicPath>Things/Plant/Grass_Leafless</leaflessGraphicPath>
            <harvestWork>40</harvestWork>
            <maxMeshCount>9</maxMeshCount>
            <visualSizeRange>0.4~0.6</visualSizeRange>
            <topWindExposure>0.4</topWindExposure>
            <wildOrder>1</wildOrder>
        </plant>
    </ThingDef>
    <ThingDef ParentName="PlantBase">
        <defName>Plant_TallGrass</defName>
        <label>tall grass</label>
        <description>Wild tall grass. Slows down anyone moving over it.</description>
        <statBases>
            <MaxHitPoints>90</MaxHitPoints>
            <Flammability>1.3</Flammability>
            <Nutrition>0.50</Nutrition>
        </statBases>
        <pathCost>14</pathCost>
        <graphicData>
            <textPath>Things/Plant/Grass</textPath>
            <graphicClass>Graphic_Random</graphicClass>
        </graphicData>
        <hideAtSnowDepth>0.5</hideAtSnowDepth>
        <ingestible />
        <plant>
            <fertilitySensitivity>0.7</fertilitySensitivity>
            <growDays>3</growDays>
            <harvestWork>60</harvestWork>
            <maxMeshCount>9</maxMeshCount>
            <visualSizeRange>0.7~0.85</visualSizeRange>
            <topWindExposure>0.4</topWindExposure>
            <wildClusterRadius>4</wildClusterRadius>
            <wildClusterWeight>10</wildClusterWeight>
            <wildOrder>1</wildOrder>
        </plant>
    </ThingDef>
    <!--====================================== Bushes
======================================== -->
    <ThingDef ParentName="BushBase">
        <defName>Plant_Bush</defName>
        <label>bush</label>
        <description>A short shrub. Does not typically talk.</description>
        <graphicData>
            <textPath>Things/Plant/Bush</textPath>
            <drawSize>1.15</drawSize>
            <shadowData>
                <volume>(0.55, 0.2, 0.2)</volume>
            </shadowData>
        </graphicData>
        <uiIconScale>0.85</uiIconScale>
        <plant>
            <growDays>3</growDays>
            <leaflessGraphicPath>Things/Plant/Bush_Leafless</leaflessGraphicPath>
        </plant>
    </ThingDef>
</Defs>
