=== dchorn/XML/Practica2.2/Actividad1/comanda.dtd
<!ELEMENT comanda (dades,articles)>
<!ELEMENT dades (numero,data,client)>
<!ELEMENT client (nom,poblacio)>
<!ELEMENT articles (article)*>
<!ELEMENT article (codi, descripcio)>

<!ELEMENT numero (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT poblacio (#PCDATA)>
<!ELEMENT codi (#PCDATA)>
<!ELEMENT descripcio (#PCDATA)>

=== dchorn/XML/Practica2.2/Actividad1/comanda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "comanda.dtd">
<comanda>
    <dades>
        <numero>13</numero>
        <data>2011-09-28</data>
        <client>
            <nom>Manel Rovira</nom>
            <poblacio>Girona</poblacio>
        </client>
    </dades>
    <articles>
        <article>
            <codi>687</codi>
            <descripcio>Ratoli</descripcio>
        </article>
        <article>
            <codi>129851</codi>
            <descripcio>Pendrive 4GB</descripcio>
        </article>
    </articles>
</comanda>
